name: Target Build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - run: make -f target.mk install_toolchain

    - run: make -j${{ steps.cpu-cores.outputs.count }} -f target.mk
